DROPOUT_R : 0.2
CLASSIFER_DROPOUT_R : 0.5
HIDDEN_SIZE: 128  #1024 # d_q 128 for clevr, 1024 for others
FLAT_OUT_SIZE: 2048
USE_BBOX_FEAT: True
USE_IMAGE_FEATURE_EXTRACTOR: true
#BBOXFEAT_EMB_SIZE: 128 #128 for clevr,   1024 for others
#IMG_FEAT_SIZE: 2052#1024
#IMG_FEAT_SIZE : 2052  # 1024

#inherit
WORD_EMBED_SIZE : 64 #300

#MFFRAA settings
SUBSPACE_DIM: 256
PROJECTION_DIM: 3072
USE_BATCHNORM: true
#VISUAL_FEATURES_DIM: 2048
CONV_LAYERS_NUM: 3 #paper default :3
