DROPOUT_R : 0.2
CLASSIFER_DROPOUT_R : 0.5
HIDDEN_SIZE: 1024
FLAT_OUT_SIZE: 2048
USE_BBOX_FEAT: True
BBOXFEAT_EMB_SIZE: 1024
IMG_FEAT_SIZE: 1024
WORD_EMBED_SIZE : 300

SUBSPACE_DIM: 256
PROJECTION_DIM: 3072
USE_BATCHNORM: true